# There should be test section before deployment

name: Test & Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
#   test:
    
  deploy:
    runs-on: ubuntu-latest
#    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Push to server, deploy, and restart pubranker
#        uses: appleboy/ssh-action@master
        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Will be finished soon."
#            cd ${{ secrets.PROJECT_PATH }}
#            ${{ secrets.SCRIPT_FILE }}
